apiVersion: v1
kind: Service
metadata:
  name: nginx-2
  labels:
    app: nginx-2
spec:
  ports:
    - port: 80
  selector:
    app: nginx-2
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-2
  labels:
    app: nginx-2
spec:
  selector:
    matchLabels:
      app: nginx-2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx-2
    spec:
      containers:
        - image: nginx
          name: nginx-2
          ports:
            - containerPort: 80
              name: nginx-2
          volumeMounts:
            - name: nginx-persistent-storage
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-persistent-storage
          persistentVolumeClaim:
            claimName: nginx-pv-claim-2
