apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx2
  name: nginx-nfs-2
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx2
  template:
    metadata:
      labels:
        run: nginx2
    spec:
      volumes:
      - name: www
        persistentVolumeClaim:
          claimName: pvc-nfs-pv2
      containers:
      - image: nginx
        name: nginx2
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
