apiVersion: v1
kind: Service
metadata:
  name: nginx-clone
  labels:
    app: nginx-clone
spec:
  ports:
    - port: 80
  selector:
    app: nginx-clone
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pv-claim-clone-1
  labels:
    app: nginx-clone
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-clone
  labels:
    app: nginx-clone
spec:
  selector:
    matchLabels:
      app: nginx-clone
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx-clone
    spec:
      containers:
        - image: nginx
          name: nginx-clone
          ports:
            - containerPort: 80
              name: nginx-clone
          volumeMounts:
            - name: nginx-clone-persistent-storage
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-clone-persistent-storage
          persistentVolumeClaim:
            claimName: nginx-pv-claim-clone-1

