---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pv-claim-clone-1
spec:
  storageClassName: rook-ceph-block
  dataSource:
    name: nginx-pv-claim
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi

