apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pv-claim-2-cloned
spec:
  storageClassName: rook-ceph-block-2
  dataSource:
    name: nginx-pv-claim-2
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
